// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int First__char_32_Person__char_32_Player_5b66f4ea00578924390ab3ef8489d129Index = 0;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "First__char_32_Person__char_32_Player_5b66f4ea00578924390ab3ef8489d129", 0 },

		};
	}
}
