// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_139248ed_214c_429b_b52c_f186ab912dcf : Vector3Binding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.destination);
			set => CastedUnityComponent.destination = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.destination;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.destination = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_822f2c45_dd75_41c2_8bb7_cf9f97452ce9 : FloatBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.stoppingDistance);
			set => CastedUnityComponent.stoppingDistance = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.stoppingDistance;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.stoppingDistance = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_3c2873fc_4b03_4fe7_8ed2_c6ea2ea286bf : Vector3Binding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.velocity);
			set => CastedUnityComponent.velocity = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.velocity;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.velocity = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_b87c4524_3b65_4f27_a966_62eea79ffa44 : Vector3Binding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.nextPosition);
			set => CastedUnityComponent.nextPosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.nextPosition;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.nextPosition = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_413394db_31f6_4d9f_b6cb_4d59fdae7c74 : FloatBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000000000010000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.baseOffset);
			set => CastedUnityComponent.baseOffset = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.baseOffset;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.baseOffset = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_5609c2c8_4c80_49ae_899e_96f1b852402d : BoolBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000000000100000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.autoTraverseOffMeshLink);
			set => CastedUnityComponent.autoTraverseOffMeshLink = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.autoTraverseOffMeshLink;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.autoTraverseOffMeshLink = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_553268cd_2f93_4d82_9e28_78d840d96f1a : BoolBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000000001000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.autoBraking);
			set => CastedUnityComponent.autoBraking = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.autoBraking;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.autoBraking = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_585429cb_8a43_48e2_8ca5_a01f19376ac0 : BoolBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000000010000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.autoRepath);
			set => CastedUnityComponent.autoRepath = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.autoRepath;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.autoRepath = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_ac6245be_a503_4060_95d0_cbe4fe505d33 : BoolBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000000100000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.isStopped);
			set => CastedUnityComponent.isStopped = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.isStopped;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.isStopped = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_b3df79af_1cd2_4364_b194_eeb245f1edd8 : IntBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000001000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.agentTypeID);
			set => CastedUnityComponent.agentTypeID = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.agentTypeID;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.agentTypeID = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_c56515bc_a37f_416a_8c38_c18374b9c46b : IntBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000010000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.walkableMask);
			set => CastedUnityComponent.walkableMask = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.walkableMask;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.walkableMask = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_fd34fd9b_7f40_4edd_ace2_14ab979ea40e : IntBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000000100000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.areaMask);
			set => CastedUnityComponent.areaMask = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.areaMask;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.areaMask = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_f8927fca_944e_4205_9523_c60023603e71 : FloatBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000001000000000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.speed);
			set => CastedUnityComponent.speed = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.speed;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.speed = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_7b454f06_20f4_46bd_b62d_70be9d870bbe : FloatBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000010000000000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.angularSpeed);
			set => CastedUnityComponent.angularSpeed = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.angularSpeed;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.angularSpeed = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_b9ad65d7_0efb_4ca1_9be1_91d9282e3652 : FloatBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000000100000000000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.acceleration);
			set => CastedUnityComponent.acceleration = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.acceleration;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.acceleration = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_28ea9f16_aa45_430c_b9e1_f3568c1b0f3b : BoolBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000001000000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.updatePosition);
			set => CastedUnityComponent.updatePosition = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.updatePosition;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.updatePosition = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_f21dbbe7_399f_4759_942f_87add79f9513 : BoolBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000010000000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.updateRotation);
			set => CastedUnityComponent.updateRotation = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.updateRotation;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.updateRotation = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_94fc98d2_992c_463f_94ea_55bd1b915150 : BoolBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000000100000000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.updateUpAxis);
			set => CastedUnityComponent.updateUpAxis = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.updateUpAxis;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.updateUpAxis = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_6cdaa561_ca27_4b9e_b883_04f4fc3f5c9c : FloatBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000001000000000000000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.radius);
			set => CastedUnityComponent.radius = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.radius;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.radius = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_dc6eea67_3a81_4a4c_b53f_079dd7e02486 : FloatBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000010000000000000000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.height);
			set => CastedUnityComponent.height = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.height;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.height = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_0a881ce5_cd0a_4843_bca5_4e609eaecc56 : IntBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000000100000000000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.avoidancePriority);
			set => CastedUnityComponent.avoidancePriority = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.avoidancePriority;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.avoidancePriority = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_83729b45_90a0_410c_9950_76aafa9cb8c6 : BoolBinding
	{
		private UnityEngine.AI.NavMeshAgent CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.AI.NavMeshAgent)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321";

		public override uint FieldMask => 0b00000000001000000000000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			return update.enabled;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_b1d09863_77c0_42c3_b83f_9c047dfb0cbc : IntBinding
	{
		private Health CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (Health)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_Health_6674255513578300028";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.maxHealth);
			set => CastedUnityComponent.maxHealth = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_Health_6674255513578300028)coherenceComponent;
			return update.maxHealth;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_Health_6674255513578300028)coherenceComponent;
			update.maxHealth = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_Health_6674255513578300028();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_4fd84e82_310e_4408_a2be_f2f8f019ae43 : DeepPositionBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localPosition);
			set => CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292)coherenceComponent;
			return update.position;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292)coherenceComponent;
			update.position = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_9c3888a3_c1f2_400d_9f02_d73aaa0a0049 : DeepScaleBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localScale);
			set => CastedUnityComponent.localScale = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292)coherenceComponent;
			return update.localScale;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292)coherenceComponent;
			update.localScale = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_795516eb_d708_4b14_a138_49acaf1df3ff : DeepRotationBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(CastedUnityComponent.localRotation);
			set => CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292)coherenceComponent;
			return update.rotation;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292)coherenceComponent;
			update.rotation = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292();
		}
	}

	public class Binding_8e3461cf8d4e4834688cfb7eaef98857_59633190_5cac_4351_9a8e_bf9a84aa1611 : Vector2Binding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Enemy_id3_UnityEngine__char_46_SpriteRenderer_5713996564254599293";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector2 Value
		{
			get => (Vector2)(UnityEngine.Vector2)(CastedUnityComponent.size);
			set => CastedUnityComponent.size = (UnityEngine.Vector2)(value);
		}

		protected override Vector2 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_SpriteRenderer_5713996564254599293)coherenceComponent;
			return update.size;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Enemy_id3_UnityEngine__char_46_SpriteRenderer_5713996564254599293)coherenceComponent;
			update.size = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Enemy_id3_UnityEngine__char_46_SpriteRenderer_5713996564254599293();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Enemy' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncEnemy_id3 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncEnemy_id3>();
			if (coherenceSync.TryGetBindingByGuid("139248ed-214c-429b-b52c-f186ab912dcf", "destination", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_destination))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_139248ed_214c_429b_b52c_f186ab912dcf();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_destination.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_destination)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).destination");
			}
			if (coherenceSync.TryGetBindingByGuid("822f2c45-dd75-41c2-8bb7-cf9f97452ce9", "stoppingDistance", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_stoppingDistance))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_822f2c45_dd75_41c2_8bb7_cf9f97452ce9();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_stoppingDistance.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_stoppingDistance)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).stoppingDistance");
			}
			if (coherenceSync.TryGetBindingByGuid("3c2873fc-4b03-4fe7-8ed2-c6ea2ea286bf", "velocity", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_velocity))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_3c2873fc_4b03_4fe7_8ed2_c6ea2ea286bf();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_velocity.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_velocity)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).velocity");
			}
			if (coherenceSync.TryGetBindingByGuid("b87c4524-3b65-4f27-a966-62eea79ffa44", "nextPosition", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_nextPosition))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_b87c4524_3b65_4f27_a966_62eea79ffa44();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_nextPosition.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_nextPosition)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).nextPosition");
			}
			if (coherenceSync.TryGetBindingByGuid("413394db-31f6-4d9f-b6cb-4d59fdae7c74", "baseOffset", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_baseOffset))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_413394db_31f6_4d9f_b6cb_4d59fdae7c74();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_baseOffset.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_baseOffset)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).baseOffset");
			}
			if (coherenceSync.TryGetBindingByGuid("5609c2c8-4c80-49ae-899e-96f1b852402d", "autoTraverseOffMeshLink", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_autoTraverseOffMeshLink))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_5609c2c8_4c80_49ae_899e_96f1b852402d();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_autoTraverseOffMeshLink.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_autoTraverseOffMeshLink)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).autoTraverseOffMeshLink");
			}
			if (coherenceSync.TryGetBindingByGuid("553268cd-2f93-4d82-9e28-78d840d96f1a", "autoBraking", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_autoBraking))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_553268cd_2f93_4d82_9e28_78d840d96f1a();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_autoBraking.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_autoBraking)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).autoBraking");
			}
			if (coherenceSync.TryGetBindingByGuid("585429cb-8a43-48e2-8ca5-a01f19376ac0", "autoRepath", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_autoRepath))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_585429cb_8a43_48e2_8ca5_a01f19376ac0();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_autoRepath.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_autoRepath)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).autoRepath");
			}
			if (coherenceSync.TryGetBindingByGuid("ac6245be-a503-4060-95d0-cbe4fe505d33", "isStopped", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_isStopped))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_ac6245be_a503_4060_95d0_cbe4fe505d33();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_isStopped.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_isStopped)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).isStopped");
			}
			if (coherenceSync.TryGetBindingByGuid("b3df79af-1cd2-4364-b194-eeb245f1edd8", "agentTypeID", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_agentTypeID))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_b3df79af_1cd2_4364_b194_eeb245f1edd8();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_agentTypeID.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_agentTypeID)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).agentTypeID");
			}
			if (coherenceSync.TryGetBindingByGuid("c56515bc-a37f-416a-8c38-c18374b9c46b", "walkableMask", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_walkableMask))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_c56515bc_a37f_416a_8c38_c18374b9c46b();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_walkableMask.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_walkableMask)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).walkableMask");
			}
			if (coherenceSync.TryGetBindingByGuid("fd34fd9b-7f40-4edd-ace2-14ab979ea40e", "areaMask", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_areaMask))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_fd34fd9b_7f40_4edd_ace2_14ab979ea40e();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_areaMask.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_areaMask)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).areaMask");
			}
			if (coherenceSync.TryGetBindingByGuid("f8927fca-944e-4205-9523-c60023603e71", "speed", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_speed))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_f8927fca_944e_4205_9523_c60023603e71();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_speed.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_speed)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).speed");
			}
			if (coherenceSync.TryGetBindingByGuid("7b454f06-20f4-46bd-b62d-70be9d870bbe", "angularSpeed", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_angularSpeed))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_7b454f06_20f4_46bd_b62d_70be9d870bbe();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_angularSpeed.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_angularSpeed)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).angularSpeed");
			}
			if (coherenceSync.TryGetBindingByGuid("b9ad65d7-0efb-4ca1-9be1-91d9282e3652", "acceleration", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_acceleration))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_b9ad65d7_0efb_4ca1_9be1_91d9282e3652();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_acceleration.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_acceleration)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).acceleration");
			}
			if (coherenceSync.TryGetBindingByGuid("28ea9f16-aa45-430c-b9e1-f3568c1b0f3b", "updatePosition", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_updatePosition))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_28ea9f16_aa45_430c_b9e1_f3568c1b0f3b();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_updatePosition.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_updatePosition)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).updatePosition");
			}
			if (coherenceSync.TryGetBindingByGuid("f21dbbe7-399f-4759-942f-87add79f9513", "updateRotation", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_updateRotation))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_f21dbbe7_399f_4759_942f_87add79f9513();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_updateRotation.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_updateRotation)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).updateRotation");
			}
			if (coherenceSync.TryGetBindingByGuid("94fc98d2-992c-463f-94ea-55bd1b915150", "updateUpAxis", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_updateUpAxis))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_94fc98d2_992c_463f_94ea_55bd1b915150();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_updateUpAxis.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_updateUpAxis)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).updateUpAxis");
			}
			if (coherenceSync.TryGetBindingByGuid("6cdaa561-ca27-4b9e-b883-04f4fc3f5c9c", "radius", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_radius))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_6cdaa561_ca27_4b9e_b883_04f4fc3f5c9c();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_radius.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_radius)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).radius");
			}
			if (coherenceSync.TryGetBindingByGuid("dc6eea67-3a81-4a4c-b53f-079dd7e02486", "height", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_height))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_dc6eea67_3a81_4a4c_b53f_079dd7e02486();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_height.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_height)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).height");
			}
			if (coherenceSync.TryGetBindingByGuid("0a881ce5-cd0a-4843-bca5-4e609eaecc56", "avoidancePriority", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_avoidancePriority))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_0a881ce5_cd0a_4843_bca5_4e609eaecc56();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_avoidancePriority.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_avoidancePriority)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).avoidancePriority");
			}
			if (coherenceSync.TryGetBindingByGuid("83729b45-90a0-410c-9950-76aafa9cb8c6", "enabled", out Binding InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_enabled))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_83729b45_90a0_410c_9950_76aafa9cb8c6();
				InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_Enemy_id3_UnityEngine__char_46_AI__char_46_NavMeshAgent_5713996564709775321_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.AI.NavMeshAgent).enabled");
			}
			if (coherenceSync.TryGetBindingByGuid("b1d09863-77c0-42c3-b83f-9c047dfb0cbc", "maxHealth", out Binding InternalEnemy_id3_Health_6674255513578300028_Enemy_id3_Health_6674255513578300028_maxHealth))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_b1d09863_77c0_42c3_b83f_9c047dfb0cbc();
				InternalEnemy_id3_Health_6674255513578300028_Enemy_id3_Health_6674255513578300028_maxHealth.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_Health_6674255513578300028_Enemy_id3_Health_6674255513578300028_maxHealth)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (Health).maxHealth");
			}
			if (coherenceSync.TryGetBindingByGuid("4fd84e82-310e-4408-a2be-f2f8f019ae43", "position", out Binding InternalEnemy_id3_UnityEngine__char_46_Transform_5713996564254599292_Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292_position))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_4fd84e82_310e_4408_a2be_f2f8f019ae43();
				InternalEnemy_id3_UnityEngine__char_46_Transform_5713996564254599292_Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292_position.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_Transform_5713996564254599292_Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292_position)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("9c3888a3-c1f2-400d-9f02-d73aaa0a0049", "localScale", out Binding InternalEnemy_id3_UnityEngine__char_46_Transform_5713996564254599292_Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292_localScale))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_9c3888a3_c1f2_400d_9f02_d73aaa0a0049();
				InternalEnemy_id3_UnityEngine__char_46_Transform_5713996564254599292_Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292_localScale.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_Transform_5713996564254599292_Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292_localScale)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).localScale");
			}
			if (coherenceSync.TryGetBindingByGuid("795516eb-d708-4b14-a138-49acaf1df3ff", "rotation", out Binding InternalEnemy_id3_UnityEngine__char_46_Transform_5713996564254599292_Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292_rotation))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_795516eb_d708_4b14_a138_49acaf1df3ff();
				InternalEnemy_id3_UnityEngine__char_46_Transform_5713996564254599292_Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292_rotation.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_Transform_5713996564254599292_Enemy_id3_UnityEngine__char_46_Transform_5713996564254599292_rotation)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("59633190-5cac-4351-9a8e-bf9a84aa1611", "size", out Binding InternalEnemy_id3_UnityEngine__char_46_SpriteRenderer_5713996564254599293_Enemy_id3_UnityEngine__char_46_SpriteRenderer_5713996564254599293_size))
			{
				var clone = new Binding_8e3461cf8d4e4834688cfb7eaef98857_59633190_5cac_4351_9a8e_bf9a84aa1611();
				InternalEnemy_id3_UnityEngine__char_46_SpriteRenderer_5713996564254599293_Enemy_id3_UnityEngine__char_46_SpriteRenderer_5713996564254599293_size.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEnemy_id3_UnityEngine__char_46_SpriteRenderer_5713996564254599293_Enemy_id3_UnityEngine__char_46_SpriteRenderer_5713996564254599293_size)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).size");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncEnemy_id3] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
