// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_cd0989dbe6b806a499067cd427b33d57_b5f1ae6b_8d64_4d31_929f_33c5958305bc : BoolBinding
	{
		private PlantObject CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (PlantObject)UnityComponent;
		}
		public override string CoherenceComponentName => "Venus__char_32_Fly__char_32_Trap_id7_PlantObject_7691798621651576192";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_PlantObject_7691798621651576192)coherenceComponent;
			return update.enabled;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_PlantObject_7691798621651576192)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Venus__char_32_Fly__char_32_Trap_id7_PlantObject_7691798621651576192();
		}
	}

	public class Binding_cd0989dbe6b806a499067cd427b33d57_9b124e2a_6e0d_445e_92aa_7ce153c904cd : Vector3Binding
	{
		private UnityEngine.BoxCollider CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.BoxCollider)UnityComponent;
		}
		public override string CoherenceComponentName => "Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_BoxCollider_2468586318803779351";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.size);
			set => CastedUnityComponent.size = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_BoxCollider_2468586318803779351)coherenceComponent;
			return update.size;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_BoxCollider_2468586318803779351)coherenceComponent;
			update.size = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_BoxCollider_2468586318803779351();
		}
	}

	public class Binding_cd0989dbe6b806a499067cd427b33d57_806613cd_eb28_4497_a67a_565169687147 : IntBinding
	{
		private Health CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (Health)UnityComponent;
		}
		public override string CoherenceComponentName => "Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.maxHealth);
			set => CastedUnityComponent.maxHealth = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369)coherenceComponent;
			return update.maxHealth;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369)coherenceComponent;
			update.maxHealth = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369();
		}
	}

	public class Binding_cd0989dbe6b806a499067cd427b33d57_7268b252_040f_4789_9ec1_44986875b2eb : IntBinding
	{
		private Health CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (Health)UnityComponent;
		}
		public override string CoherenceComponentName => "Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.currentHealth);
			set => CastedUnityComponent.currentHealth = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369)coherenceComponent;
			return update.currentHealth;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369)coherenceComponent;
			update.currentHealth = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369();
		}
	}

	public class Binding_cd0989dbe6b806a499067cd427b33d57_123ce12f_0726_46a1_92b0_82b10146c912 : DeepPositionBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localPosition);
			set => CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718)coherenceComponent;
			return update.position;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718)coherenceComponent;
			update.position = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718();
		}
	}

	public class Binding_cd0989dbe6b806a499067cd427b33d57_fe919b5d_8672_49e9_a7c1_8e4fb332701c : DeepScaleBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localScale);
			set => CastedUnityComponent.localScale = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718)coherenceComponent;
			return update.localScale;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718)coherenceComponent;
			update.localScale = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718();
		}
	}

	public class Binding_cd0989dbe6b806a499067cd427b33d57_d43fda27_6c8a_482e_a5d6_6ebae1a6bb83 : DeepRotationBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(CastedUnityComponent.localRotation);
			set => CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718)coherenceComponent;
			return update.rotation;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718)coherenceComponent;
			update.rotation = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718();
		}
	}

	public class Binding_cd0989dbe6b806a499067cd427b33d57_c9e8a53e_9ba6_4a9e_9f31_b08f6537066e : Vector2Binding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_SpriteRenderer_7956612112273618293";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector2 Value
		{
			get => (Vector2)(UnityEngine.Vector2)(CastedUnityComponent.size);
			set => CastedUnityComponent.size = (UnityEngine.Vector2)(value);
		}

		protected override Vector2 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_SpriteRenderer_7956612112273618293)coherenceComponent;
			return update.size;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_SpriteRenderer_7956612112273618293)coherenceComponent;
			update.size = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_SpriteRenderer_7956612112273618293();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Venus Fly Trap' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncVenus__char_32_Fly__char_32_Trap_id7 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncVenus__char_32_Fly__char_32_Trap_id7>();
			if (coherenceSync.TryGetBindingByGuid("b5f1ae6b-8d64-4d31-929f-33c5958305bc", "enabled", out Binding InternalVenus__char_32_Fly__char_32_Trap_id7_PlantObject_7691798621651576192_Venus__char_32_Fly__char_32_Trap_id7_PlantObject_7691798621651576192_enabled))
			{
				var clone = new Binding_cd0989dbe6b806a499067cd427b33d57_b5f1ae6b_8d64_4d31_929f_33c5958305bc();
				InternalVenus__char_32_Fly__char_32_Trap_id7_PlantObject_7691798621651576192_Venus__char_32_Fly__char_32_Trap_id7_PlantObject_7691798621651576192_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVenus__char_32_Fly__char_32_Trap_id7_PlantObject_7691798621651576192_Venus__char_32_Fly__char_32_Trap_id7_PlantObject_7691798621651576192_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (PlantObject).enabled");
			}
			if (coherenceSync.TryGetBindingByGuid("9b124e2a-6e0d-445e-92aa-7ce153c904cd", "size", out Binding InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_BoxCollider_2468586318803779351_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_BoxCollider_2468586318803779351_size))
			{
				var clone = new Binding_cd0989dbe6b806a499067cd427b33d57_9b124e2a_6e0d_445e_92aa_7ce153c904cd();
				InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_BoxCollider_2468586318803779351_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_BoxCollider_2468586318803779351_size.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_BoxCollider_2468586318803779351_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_BoxCollider_2468586318803779351_size)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.BoxCollider).size");
			}
			if (coherenceSync.TryGetBindingByGuid("806613cd-eb28-4497-a67a-565169687147", "maxHealth", out Binding InternalVenus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_maxHealth))
			{
				var clone = new Binding_cd0989dbe6b806a499067cd427b33d57_806613cd_eb28_4497_a67a_565169687147();
				InternalVenus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_maxHealth.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVenus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_maxHealth)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (Health).maxHealth");
			}
			if (coherenceSync.TryGetBindingByGuid("7268b252-040f-4789-9ec1-44986875b2eb", "currentHealth", out Binding InternalVenus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_currentHealth))
			{
				var clone = new Binding_cd0989dbe6b806a499067cd427b33d57_7268b252_040f_4789_9ec1_44986875b2eb();
				InternalVenus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_currentHealth.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVenus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_currentHealth)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (Health).currentHealth");
			}
			if (coherenceSync.TryGetBindingByGuid("123ce12f-0726-46a1-92b0-82b10146c912", "position", out Binding InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_position))
			{
				var clone = new Binding_cd0989dbe6b806a499067cd427b33d57_123ce12f_0726_46a1_92b0_82b10146c912();
				InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_position.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_position)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("fe919b5d-8672-49e9-a7c1-8e4fb332701c", "localScale", out Binding InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_localScale))
			{
				var clone = new Binding_cd0989dbe6b806a499067cd427b33d57_fe919b5d_8672_49e9_a7c1_8e4fb332701c();
				InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_localScale.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_localScale)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).localScale");
			}
			if (coherenceSync.TryGetBindingByGuid("d43fda27-6c8a-482e-a5d6-6ebae1a6bb83", "rotation", out Binding InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_rotation))
			{
				var clone = new Binding_cd0989dbe6b806a499067cd427b33d57_d43fda27_6c8a_482e_a5d6_6ebae1a6bb83();
				InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_rotation.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_Transform_8238115587357776718_rotation)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("c9e8a53e-9ba6-4a9e-9f31-b08f6537066e", "size", out Binding InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_SpriteRenderer_7956612112273618293_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_SpriteRenderer_7956612112273618293_size))
			{
				var clone = new Binding_cd0989dbe6b806a499067cd427b33d57_c9e8a53e_9ba6_4a9e_9f31_b08f6537066e();
				InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_SpriteRenderer_7956612112273618293_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_SpriteRenderer_7956612112273618293_size.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVenus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_SpriteRenderer_7956612112273618293_Venus__char_32_Fly__char_32_Trap_id7_UnityEngine__char_46_SpriteRenderer_7956612112273618293_size)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).size");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncVenus__char_32_Fly__char_32_Trap_id7] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
