// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_4c242586da6a31949973a28c5fabc675_75e35e40_2d57_4674_ad17_023abb4e5e36 : Vector2Binding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Spawner_id2_UnityEngine__char_46_SpriteRenderer_2011534467780421881";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector2 Value
		{
			get => (Vector2)(UnityEngine.Vector2)(CastedUnityComponent.size);
			set => CastedUnityComponent.size = (UnityEngine.Vector2)(value);
		}

		protected override Vector2 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Spawner_id2_UnityEngine__char_46_SpriteRenderer_2011534467780421881)coherenceComponent;
			return update.size;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Spawner_id2_UnityEngine__char_46_SpriteRenderer_2011534467780421881)coherenceComponent;
			update.size = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Spawner_id2_UnityEngine__char_46_SpriteRenderer_2011534467780421881();
		}
	}

	public class Binding_4c242586da6a31949973a28c5fabc675_69989bad_83c1_41cb_b613_b26e342fb6e4 : ReferenceBinding
	{
		private AISpawner CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (AISpawner)UnityComponent;
		}
		public override string CoherenceComponentName => "Spawner_id2_AISpawner_2011534467780421880";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.enemyPrefab);
			set => CastedUnityComponent.enemyPrefab = coherenceSync.MonoBridge.EntityIdToGameObject(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Spawner_id2_AISpawner_2011534467780421880)coherenceComponent;
			return update.enemyPrefab;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Spawner_id2_AISpawner_2011534467780421880)coherenceComponent;
			update.enemyPrefab = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Spawner_id2_AISpawner_2011534467780421880();
		}
	}

	public class Binding_4c242586da6a31949973a28c5fabc675_7a20d39f_326f_470e_8184_331cfde8ba24 : FloatBinding
	{
		private AISpawner CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (AISpawner)UnityComponent;
		}
		public override string CoherenceComponentName => "Spawner_id2_AISpawner_2011534467780421880";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.spawnDelay);
			set => CastedUnityComponent.spawnDelay = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Spawner_id2_AISpawner_2011534467780421880)coherenceComponent;
			return update.spawnDelay;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Spawner_id2_AISpawner_2011534467780421880)coherenceComponent;
			update.spawnDelay = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Spawner_id2_AISpawner_2011534467780421880();
		}
	}

	public class Binding_4c242586da6a31949973a28c5fabc675_1e387865_0ba3_49f9_a556_318ae569aee0 : BoolBinding
	{
		private AISpawner CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (AISpawner)UnityComponent;
		}
		public override string CoherenceComponentName => "Spawner_id2_AISpawner_2011534467780421880";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Spawner_id2_AISpawner_2011534467780421880)coherenceComponent;
			return update.enabled;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Spawner_id2_AISpawner_2011534467780421880)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Spawner_id2_AISpawner_2011534467780421880();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Spawner' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncSpawner_id2 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands		
		private AISpawner Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17_CommandTarget;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncSpawner_id2>();
			if (coherenceSync.TryGetBindingByGuid("405d0a8b-c3f8-44f9-b6c2-0b2fff12fe17", "SpawnNextWave", out Binding Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17))
			{
				Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17_CommandTarget = (AISpawner)Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("AISpawner.SpawnNextWave", "()",
				SendCommand_Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17, ReceiveLocalCommand_Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17, MessageTarget.AuthorityOnly, Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (SpawnNextWave)");
			}
			if (coherenceSync.TryGetBindingByGuid("75e35e40-2d57-4674-ad17-023abb4e5e36", "size", out Binding InternalSpawner_id2_UnityEngine__char_46_SpriteRenderer_2011534467780421881_Spawner_id2_UnityEngine__char_46_SpriteRenderer_2011534467780421881_size))
			{
				var clone = new Binding_4c242586da6a31949973a28c5fabc675_75e35e40_2d57_4674_ad17_023abb4e5e36();
				InternalSpawner_id2_UnityEngine__char_46_SpriteRenderer_2011534467780421881_Spawner_id2_UnityEngine__char_46_SpriteRenderer_2011534467780421881_size.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSpawner_id2_UnityEngine__char_46_SpriteRenderer_2011534467780421881_Spawner_id2_UnityEngine__char_46_SpriteRenderer_2011534467780421881_size)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).size");
			}
			if (coherenceSync.TryGetBindingByGuid("69989bad-83c1-41cb-b613-b26e342fb6e4", "enemyPrefab", out Binding InternalSpawner_id2_AISpawner_2011534467780421880_Spawner_id2_AISpawner_2011534467780421880_enemyPrefab))
			{
				var clone = new Binding_4c242586da6a31949973a28c5fabc675_69989bad_83c1_41cb_b613_b26e342fb6e4();
				InternalSpawner_id2_AISpawner_2011534467780421880_Spawner_id2_AISpawner_2011534467780421880_enemyPrefab.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSpawner_id2_AISpawner_2011534467780421880_Spawner_id2_AISpawner_2011534467780421880_enemyPrefab)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (AISpawner).enemyPrefab");
			}
			if (coherenceSync.TryGetBindingByGuid("7a20d39f-326f-470e-8184-331cfde8ba24", "spawnDelay", out Binding InternalSpawner_id2_AISpawner_2011534467780421880_Spawner_id2_AISpawner_2011534467780421880_spawnDelay))
			{
				var clone = new Binding_4c242586da6a31949973a28c5fabc675_7a20d39f_326f_470e_8184_331cfde8ba24();
				InternalSpawner_id2_AISpawner_2011534467780421880_Spawner_id2_AISpawner_2011534467780421880_spawnDelay.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSpawner_id2_AISpawner_2011534467780421880_Spawner_id2_AISpawner_2011534467780421880_spawnDelay)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (AISpawner).spawnDelay");
			}
			if (coherenceSync.TryGetBindingByGuid("1e387865-0ba3-49f9-a556-318ae569aee0", "enabled", out Binding InternalSpawner_id2_AISpawner_2011534467780421880_Spawner_id2_AISpawner_2011534467780421880_enabled))
			{
				var clone = new Binding_4c242586da6a31949973a28c5fabc675_1e387865_0ba3_49f9_a556_318ae569aee0();
				InternalSpawner_id2_AISpawner_2011534467780421880_Spawner_id2_AISpawner_2011534467780421880_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSpawner_id2_AISpawner_2011534467780421880_Spawner_id2_AISpawner_2011534467780421880_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (AISpawner).enabled");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}
		void SendCommand_Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17(MessageTarget target, object[] args)
		{
			var command = new Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17();
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17(MessageTarget target, object[] args)
		{
			var command = new Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17();
			ReceiveCommand_Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17(command);
		}

		void ReceiveCommand_Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17(Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17 command)
		{
			var target = Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17_CommandTarget;
			target.SpawnNextWave();
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17 castedCommand:
					ReceiveCommand_Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncSpawner_id2] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
