// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_e6b57ddcc936ef24db26545e3576fe23_ea46d736_3a8d_4a65_a123_b9c8ee2d61bf : BoolBinding
	{
		private PlantObject CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (PlantObject)UnityComponent;
		}
		public override string CoherenceComponentName => "Lily__char_32_Pad_id5_PlantObject_703798951448450330";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_PlantObject_703798951448450330)coherenceComponent;
			return update.enabled;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_PlantObject_703798951448450330)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Lily__char_32_Pad_id5_PlantObject_703798951448450330();
		}
	}

	public class Binding_e6b57ddcc936ef24db26545e3576fe23_11fb3203_f393_4b1d_8c5c_af8be855247b : Vector3Binding
	{
		private UnityEngine.BoxCollider CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.BoxCollider)UnityComponent;
		}
		public override string CoherenceComponentName => "Lily__char_32_Pad_id5_UnityEngine__char_46_BoxCollider_7574956677122350200";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.size);
			set => CastedUnityComponent.size = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_UnityEngine__char_46_BoxCollider_7574956677122350200)coherenceComponent;
			return update.size;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_UnityEngine__char_46_BoxCollider_7574956677122350200)coherenceComponent;
			update.size = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Lily__char_32_Pad_id5_UnityEngine__char_46_BoxCollider_7574956677122350200();
		}
	}

	public class Binding_e6b57ddcc936ef24db26545e3576fe23_5b234f35_21e7_456f_8c4d_120cfacfb9cd : IntBinding
	{
		private Health CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (Health)UnityComponent;
		}
		public override string CoherenceComponentName => "Lily__char_32_Pad_id5_Health_7105588657738653232";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.maxHealth);
			set => CastedUnityComponent.maxHealth = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_Health_7105588657738653232)coherenceComponent;
			return update.maxHealth;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_Health_7105588657738653232)coherenceComponent;
			update.maxHealth = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Lily__char_32_Pad_id5_Health_7105588657738653232();
		}
	}

	public class Binding_e6b57ddcc936ef24db26545e3576fe23_775bcbea_1240_4f4c_b030_968c55400577 : DeepPositionBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localPosition);
			set => CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821)coherenceComponent;
			return update.position;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821)coherenceComponent;
			update.position = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821();
		}
	}

	public class Binding_e6b57ddcc936ef24db26545e3576fe23_669d3b22_7197_453a_9d69_49e629483d7d : DeepRotationBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(CastedUnityComponent.localRotation);
			set => CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821)coherenceComponent;
			return update.rotation;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821)coherenceComponent;
			update.rotation = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821();
		}
	}

	public class Binding_e6b57ddcc936ef24db26545e3576fe23_ff6852a4_3def_4271_9935_5151066d7092 : DeepScaleBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localScale);
			set => CastedUnityComponent.localScale = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821)coherenceComponent;
			return update.localScale;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821)coherenceComponent;
			update.localScale = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821();
		}
	}

	public class Binding_e6b57ddcc936ef24db26545e3576fe23_2204e6bd_b85c_43c1_b592_417295cbe968 : Vector2Binding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Lily__char_32_Pad_id5_UnityEngine__char_46_SpriteRenderer_7190805722808687280";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector2 Value
		{
			get => (Vector2)(UnityEngine.Vector2)(CastedUnityComponent.size);
			set => CastedUnityComponent.size = (UnityEngine.Vector2)(value);
		}

		protected override Vector2 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_UnityEngine__char_46_SpriteRenderer_7190805722808687280)coherenceComponent;
			return update.size;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Lily__char_32_Pad_id5_UnityEngine__char_46_SpriteRenderer_7190805722808687280)coherenceComponent;
			update.size = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Lily__char_32_Pad_id5_UnityEngine__char_46_SpriteRenderer_7190805722808687280();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Lily Pad' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncLily__char_32_Pad_id5 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncLily__char_32_Pad_id5>();
			if (coherenceSync.TryGetBindingByGuid("ea46d736-3a8d-4a65-a123-b9c8ee2d61bf", "enabled", out Binding InternalLily__char_32_Pad_id5_PlantObject_703798951448450330_Lily__char_32_Pad_id5_PlantObject_703798951448450330_enabled))
			{
				var clone = new Binding_e6b57ddcc936ef24db26545e3576fe23_ea46d736_3a8d_4a65_a123_b9c8ee2d61bf();
				InternalLily__char_32_Pad_id5_PlantObject_703798951448450330_Lily__char_32_Pad_id5_PlantObject_703798951448450330_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalLily__char_32_Pad_id5_PlantObject_703798951448450330_Lily__char_32_Pad_id5_PlantObject_703798951448450330_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (PlantObject).enabled");
			}
			if (coherenceSync.TryGetBindingByGuid("11fb3203-f393-4b1d-8c5c-af8be855247b", "size", out Binding InternalLily__char_32_Pad_id5_UnityEngine__char_46_BoxCollider_7574956677122350200_Lily__char_32_Pad_id5_UnityEngine__char_46_BoxCollider_7574956677122350200_size))
			{
				var clone = new Binding_e6b57ddcc936ef24db26545e3576fe23_11fb3203_f393_4b1d_8c5c_af8be855247b();
				InternalLily__char_32_Pad_id5_UnityEngine__char_46_BoxCollider_7574956677122350200_Lily__char_32_Pad_id5_UnityEngine__char_46_BoxCollider_7574956677122350200_size.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalLily__char_32_Pad_id5_UnityEngine__char_46_BoxCollider_7574956677122350200_Lily__char_32_Pad_id5_UnityEngine__char_46_BoxCollider_7574956677122350200_size)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.BoxCollider).size");
			}
			if (coherenceSync.TryGetBindingByGuid("5b234f35-21e7-456f-8c4d-120cfacfb9cd", "maxHealth", out Binding InternalLily__char_32_Pad_id5_Health_7105588657738653232_Lily__char_32_Pad_id5_Health_7105588657738653232_maxHealth))
			{
				var clone = new Binding_e6b57ddcc936ef24db26545e3576fe23_5b234f35_21e7_456f_8c4d_120cfacfb9cd();
				InternalLily__char_32_Pad_id5_Health_7105588657738653232_Lily__char_32_Pad_id5_Health_7105588657738653232_maxHealth.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalLily__char_32_Pad_id5_Health_7105588657738653232_Lily__char_32_Pad_id5_Health_7105588657738653232_maxHealth)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (Health).maxHealth");
			}
			if (coherenceSync.TryGetBindingByGuid("775bcbea-1240-4f4c-b030-968c55400577", "position", out Binding InternalLily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_position))
			{
				var clone = new Binding_e6b57ddcc936ef24db26545e3576fe23_775bcbea_1240_4f4c_b030_968c55400577();
				InternalLily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_position.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalLily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_position)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("669d3b22-7197-453a-9d69-49e629483d7d", "rotation", out Binding InternalLily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_rotation))
			{
				var clone = new Binding_e6b57ddcc936ef24db26545e3576fe23_669d3b22_7197_453a_9d69_49e629483d7d();
				InternalLily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_rotation.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalLily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_rotation)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("ff6852a4-3def-4271-9935-5151066d7092", "localScale", out Binding InternalLily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_localScale))
			{
				var clone = new Binding_e6b57ddcc936ef24db26545e3576fe23_ff6852a4_3def_4271_9935_5151066d7092();
				InternalLily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_localScale.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalLily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_Lily__char_32_Pad_id5_UnityEngine__char_46_Transform_6732670781276190821_localScale)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).localScale");
			}
			if (coherenceSync.TryGetBindingByGuid("2204e6bd-b85c-43c1-b592-417295cbe968", "size", out Binding InternalLily__char_32_Pad_id5_UnityEngine__char_46_SpriteRenderer_7190805722808687280_Lily__char_32_Pad_id5_UnityEngine__char_46_SpriteRenderer_7190805722808687280_size))
			{
				var clone = new Binding_e6b57ddcc936ef24db26545e3576fe23_2204e6bd_b85c_43c1_b592_417295cbe968();
				InternalLily__char_32_Pad_id5_UnityEngine__char_46_SpriteRenderer_7190805722808687280_Lily__char_32_Pad_id5_UnityEngine__char_46_SpriteRenderer_7190805722808687280_size.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalLily__char_32_Pad_id5_UnityEngine__char_46_SpriteRenderer_7190805722808687280_Lily__char_32_Pad_id5_UnityEngine__char_46_SpriteRenderer_7190805722808687280_size)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).size");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncLily__char_32_Pad_id5] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
