// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;

	public struct Lily__char_32_Pad : IEntityInput
	{
		public uint GetComponentType() => Definition.InternalLily__char_32_Pad;

		private readonly bool isRemoteInput;

		public Lily__char_32_Pad
		(
			bool isRemoteInput
		)
		{
			this.isRemoteInput = isRemoteInput;
		}

		public override string ToString()
		{
			return isRemoteInput
				? $""
				: $"";
		}

		public static void Serialize(Lily__char_32_Pad inputData, IOutProtocolBitStream bitStream)
		{
		}

		public static Lily__char_32_Pad Deserialize(IInProtocolBitStream bitStream)
		{

			return new Lily__char_32_Pad
			(
				true
			);
		}
	}
}
