// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalSpawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17;

		public static void Serialize(Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Spawner_id2_AISpawner__char_46_SpawnNextWave_405d0a8b_c3f8_44f9_b6c2_0b2fff12fe17
			(
			){};
		}
	}
}
