// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Spawner_id2_AISpawner_2011534467780421880 : ICoherenceComponentData
	{
		public SerializeEntityID enemyPrefab;
		public float spawnDelay;
		public bool enabled;

		public override string ToString()
		{
			return $"Spawner_id2_AISpawner_2011534467780421880(enemyPrefab: {enemyPrefab}, spawnDelay: {spawnDelay}, enabled: {enabled})";
		}

		public uint GetComponentType() => Definition.InternalSpawner_id2_AISpawner_2011534467780421880;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Spawner_id2_AISpawner_2011534467780421880)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				enemyPrefab = other.enemyPrefab;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				spawnDelay = other.spawnDelay;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				enabled = other.enabled;
			}
			mask >>= 1;
			return this;
		}

		public static void Serialize(Spawner_id2_AISpawner_2011534467780421880 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteEntity(data.enemyPrefab);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.spawnDelay, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteBool(data.enabled);
			}
			mask >>= 1;
		}

		public static (Spawner_id2_AISpawner_2011534467780421880, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Spawner_id2_AISpawner_2011534467780421880();
	
			if (bitStream.ReadMask())
			{
				val.enemyPrefab = bitStream.ReadEntity();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.spawnDelay = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.enabled = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000000100;
			}
			return (val, mask, null);
		}
		public static (Spawner_id2_AISpawner_2011534467780421880, uint, uint?) DeserializeArchetypeSpawner_4c242586da6a31949973a28c5fabc675_Spawner_id2_AISpawner_2011534467780421880_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Spawner_id2_AISpawner_2011534467780421880();
			if (bitStream.ReadMask())
			{
				val.enemyPrefab = bitStream.ReadEntity();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.spawnDelay = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.enabled = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000000100;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Spawner_id2_AISpawner_2011534467780421880?;
	
		}
	}
}