// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;

	public struct Spores : IEntityInput
	{
		public uint GetComponentType() => Definition.InternalSpores;

		private readonly bool isRemoteInput;

		public Spores
		(
			bool isRemoteInput
		)
		{
			this.isRemoteInput = isRemoteInput;
		}

		public override string ToString()
		{
			return isRemoteInput
				? $""
				: $"";
		}

		public static void Serialize(Spores inputData, IOutProtocolBitStream bitStream)
		{
		}

		public static Spores Deserialize(IInProtocolBitStream bitStream)
		{

			return new Spores
			(
				true
			);
		}
	}
}
