// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;

	public struct Venus__char_32_Fly__char_32_Trap : IEntityInput
	{
		public uint GetComponentType() => Definition.InternalVenus__char_32_Fly__char_32_Trap;

		private readonly bool isRemoteInput;

		public Venus__char_32_Fly__char_32_Trap
		(
			bool isRemoteInput
		)
		{
			this.isRemoteInput = isRemoteInput;
		}

		public override string ToString()
		{
			return isRemoteInput
				? $""
				: $"";
		}

		public static void Serialize(Venus__char_32_Fly__char_32_Trap inputData, IOutProtocolBitStream bitStream)
		{
		}

		public static Venus__char_32_Fly__char_32_Trap Deserialize(IInProtocolBitStream bitStream)
		{

			return new Venus__char_32_Fly__char_32_Trap
			(
				true
			);
		}
	}
}
