// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369 : ICoherenceComponentData
	{
		public int maxHealth;

		public override string ToString()
		{
			return $"Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369(maxHealth: {maxHealth})";
		}

		public uint GetComponentType() => Definition.InternalVenus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	
		private static readonly int _maxHealth_Min = -2147483648;
		private static readonly int _maxHealth_Max = 2147483647;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				maxHealth = other.maxHealth;
			}
			mask >>= 1;
			return this;
		}

		public static void Serialize(Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.maxHealth, _maxHealth_Min, _maxHealth_Max, "Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369.maxHealth");
				data.maxHealth = Coherence.Utils.Bounds.Clamp(data.maxHealth, _maxHealth_Min, _maxHealth_Max);
				bitStream.WriteIntegerRange(data.maxHealth, 32, -2147483648);
			}
			mask >>= 1;
		}

		public static (Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369();
	
			if (bitStream.ReadMask())
			{
				val.maxHealth = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000001;
			}
			return (val, mask, null);
		}
		public static (Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369, uint, uint?) DeserializeArchetypeVenus__char_32_Fly__char_32_Trap_cd0989dbe6b806a499067cd427b33d57_Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369();
			if (bitStream.ReadMask())
			{
				val.maxHealth = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Venus__char_32_Fly__char_32_Trap_id7_Health_1802279656568455369?;
	
		}
	}
}